## Analytical Method

In [7]:
import numpy as np

A = np.array([[8, -2, 1, 3], [1, -5, 2, 1],[-1, 2, 7, 2],[2 ,-1, 3, 8]],dtype=float)
b = np.array([9, -7, -1, 5],dtype=float)

A_inverse = np.linalg.inv(A)
result = np.matmul(A_inverse, b)
result

array([ 1.32323232,  1.56565657, -0.60606061,  0.71717172])

In [9]:
import numpy as np

def MyGauss(A,b):
    
    for k in range(len(A)-1):
        
        if A[k,k] == 0.0:
            break
        
        for i in range(k+1, len(A)):
            
            pivot = A[i,k]/A[k,k]
            
            #need to add in another loop since b and A can't be in same loop
            #because A goes through more iterations whereas B requires only one
            #calculation per row BUT they both share a common pivot
            
            #this extra loop will go through every row for a certain column below the diagonal of the matrix
            for j in range(k, len(A)):
                A[i,j] = A[i,j] - pivot * A[k,j]
            
            
            b[i] = b[i] - pivot * b[k]
    
    x = np.zeros(len(b))
    
    #working backwards
    for i in range(len(b)-1,-1,-1):
        
        #need to start off with last row, this value is needed for all other rows
        x[i] = b[i]/A[i,i]
    
        #and now work way backwards substituting in values already calculated
        for j in range(i+1,len(b)):
            
            x[i] = x[i] - ((A[i,j] * x[j]) / A[i,i])

    return A,b,x

In [8]:
A = np.array([[8, -2, 1, 3], [1, -5, 2, 1],[-1, 2, 7, 2],[2 ,-1, 3, 8]],dtype=float)
b = np.array([9, -7, -1, 5],dtype=float)

MyGauss(A,b)

(array([[ 8.        , -2.        ,  1.        ,  3.        ],
        [ 0.        , -4.75      ,  1.875     ,  0.625     ],
        [ 0.        ,  0.        ,  7.81578947,  2.60526316],
        [ 0.        ,  0.        ,  0.        ,  6.33333333]]),
 array([ 9.        , -8.125     , -2.86842105,  4.54208754]),
 array([ 1.32323232,  1.56565657, -0.60606061,  0.71717172]))